spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.SQL: DEBUG