spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:h2:mem:AZ
logging:
  level:
    org.hibernate.SQL: DEBUG